1.  Matrix Operation
    Perform the following operations on the given matrices:

    A=[[2 -1], [​0 3​]]

    B=[[1 ​ 2], [-3 4​]]

    a. A+B

    b. AB

    c. 3A−2B

In [3]:

import numpy as np

A=np.array([
    [2   , -1],
    [0,3]
])

print("A=",A)

B=np.array([
    [1,2],
    [-3,4]
])

print("B=",B)

AB = np.dot(A, B)      

print("AB=",AB)

add = A + B

print("A+B=",add)

sub = 3*A - 2*B

print("3A-2B=",sub)


A= [[ 2 -1]
 [ 0  3]]
B= [[ 1  2]
 [-3  4]]
AB= [[ 5  0]
 [-9 12]]
A+B= [[ 3  1]
 [-3  7]]
3A-2B= [[ 4 -7]
 [ 6  1]]


2.  Determinants and Inverses 

    Find the determinant of A.
    
    Determine whether A is invertible. If yes, calculate A−1.
 

In [4]:
import numpy as np

# Define matrix A
A = np.array([
    [4, 3],
    [2, 5]]
    )

# Finding determinant
determinant_A = np.linalg.det(A)
print("Determinant of A:", determinant_A)

# Checking if A is inversible
if determinant_A != 0:
    A_inv = np.linalg.inv(A)
    print("Inverse of A:\n", A_inv)
else:
    print("Matrix A is not inversivle")

Determinant of A: 14.000000000000004
Inverse of A:
 [[ 0.35714286 -0.21428571]
 [-0.14285714  0.28571429]]


3.  Eigenvalues and Eigenvectors  

    Compute the eigenvalues and eigenvectors of the matrix:
    
    C=[[4    1], [​−2       1]​]

In [5]:
import numpy.linalg as LA
import numpy as np
A=np.array([[2,-1],[0,3]])
LA.det(A)

C=np.array([[4,1],[-2,1]])

print("Matrix C is")

print(C)

eigenvalues,eigenvectors=np.linalg.eig(A)

print("Eigenvalue(first)")
print(eigenvalues[0])

print("Corresponding eigenvector is ")
print(eigenvectors[:, 0])

print("Eigenvalue(second)")
print(eigenvalues[1])

print("Corresponding eigenvector is ")
print(eigenvectors[:, 1])

Matrix C is
[[ 4  1]
 [-2  1]]
Eigenvalue(first)
2.0
Corresponding eigenvector is 
[1. 0.]
Eigenvalue(second)
3.0
Corresponding eigenvector is 
[-0.70710678  0.70710678]


4. You are given a dataset of cars with the following features:Number of cylinders (x1​)Engine size in liters (x2​)Horsepower (x3)

    car 1:

    x1: 4

    x2:  1.5

    x3: 100

    and price: 20

    car 2:

    x1: 6

    x2:  2.0

    x3: 150

    and price: 30


    Then, find the price of a car 3 with features

    x1: 8

    x2:  3.0

    x3: 200

    price:?

In [6]:
print(" Feature Matrix:")
X=np.array([
    [4,1.5,100],
    [6,2,150]
])
print(X)
print("Price Vector:")
y=np.array([
    [20],
    [30]
])
print(y)
# calculating the  coefficient using pseudo inverse
beta=np.linalg.pinv(X).dot(y)
#finding the price of car3
print("Feature Matrix of car3")
X1=np.array([
    [8,3,200]
])
print(X1)
priceofcar3= X1 @ beta
print("The price of car 3 is")
print(priceofcar3)

 Feature Matrix:
[[  4.    1.5 100. ]
 [  6.    2.  150. ]]
Price Vector:
[[20]
 [30]]
Feature Matrix of car3
[[  8   3 200]]
The price of car 3 is
[[40.]]
